###
/// Health check
GET http://localhost:3000/ HTTP/2

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
/// Create a new album
POST http://localhost:3000/api/album HTTP/2
Authorization: secret

secret

> {%
    /// extract new album
    let location = response.headers.valueOf("LOCATION").toString()
    client.global.set("album", location)
    // request.variables.set("album", location)
%}

###
/// upload image
POST http://localhost:3000/api{{album}} HTTP/2
Authorization: secret
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testbild.jpg"

// The 'testbild.jpg' file will be uploaded
< ./testbild.jpg
--boundary
Content-Disposition: form-data; name="name"; filename="testbild.jpg"

testbild.jpg

###
/// delete image
DELETE http://localhost:3000/apiapi{{album}}/f80d31b6-8193-40a4-92ff-fcc6b1f6f284

###
// delete album
DELETE http://localhost:3000/api{{album}} HTTP/2

